### ISSUE TITLE
Search key issues

### ISSUE THREAD

**Issue by hardheid** [williamxie11/glassdoor-interview-scraper#2]
Thank you for sharing this great tool. When I run the script login works and the tool takes you to the search page. The tool, however, does not put any information in the search boxes and terminal throws the following error:
File "/home/maus/git/linkedin-jobs-scraper/client.py", line 422, in enter_search_keys
    (By.ID, "keyword-search-box")

The same happens with the related glassdoor-salary-shaper with terminal showing the following error:
TimeoutException! city/title field or search button not found on glassdoor.com

I'm guessing that Glassdoor has changed the box info and that the scraper.py script requires modification. Any way to resolve this?

**Comment by williamxie11** [comment]
Hi @hardheid. I'm not sure what modifications were made but this error is specific to Selenium not being able to find the element specified by the given ID. You might want to double check if the ID is correct or find a different way to get where you need to go on Glassdoor. I've encountered some weird flakiness with Selenium in the past - perhaps you might want to try a different method.

The original method in the script is that after login it should directly go to the companyURL that is specified in the script and start scraping reviews on that company page.
